**NumPy**

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.zeros((3,5))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.arange(0,110,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [6]:
np.full((5,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [7]:
np.full((2,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [8]:
np.random.random((2,2))

array([[0.44264043, 0.83513339],
       [0.12081184, 0.89357323]])

In [9]:
a=np.array(([1,2,3],[4,5,6]))

In [10]:
x=a.shape

In [11]:
list(x)

[2, 3]

In [12]:
a.shape =(3,2)

In [13]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
a.shape =(2,3)

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a.shape[0]

2

In [17]:
a.shape[1]

3

In [18]:
x=np.full((5,8),9)

In [19]:
x

array([[9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9]])

In [20]:
x.shape

(5, 8)

In [21]:
x.shape[0]

5

In [22]:
x.shape[1]

8

In [23]:
a.size

6

In [24]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
x.size

40

In [26]:
a=np.arange(10)

In [27]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x

array([[9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9]])

In [29]:
x.ndim

2

In [30]:
a.ndim

1

In [31]:
a.dtype

dtype('int64')

In [32]:
x.dtype

dtype('int64')

In [33]:
x=np.linspace(1,10,20)

In [34]:
x

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [35]:
x.dtype

dtype('float64')

In [36]:
a=np.arange(9)

In [37]:
a.shape=(3,3)

In [38]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
b=np.full((3),1)

In [40]:
b

array([1, 1, 1])

In [41]:
a+b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
a-b

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [43]:
b-a

array([[ 1,  0, -1],
       [-2, -3, -4],
       [-5, -6, -7]])

In [44]:
x="abin joseph" 

In [45]:
x

'abin joseph'

In [46]:
x[0:4]

'abin'

In [47]:
x[5:11]

'joseph'

In [48]:
x[-6:-1]

'josep'

In [49]:
x[-1:]

'h'

In [50]:
x[::-1]

'hpesoj niba'

In [51]:
x[:-1]

'abin josep'

In [52]:
x[:5]

'abin '

In [53]:
x[5:]

'joseph'

In [54]:
x[:4]

'abin'

In [55]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
a+=1

In [57]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
a[0]

array([1, 2, 3])

In [59]:
a[::1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
a[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [61]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [63]:
a[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
a[:3,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [65]:
a[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
a[:1,:1]

array([[1]])

In [67]:
a[:1,:2]

array([[1, 2]])

In [68]:
a[:1,:3]

array([[1, 2, 3]])

In [69]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
a[1]

array([4, 5, 6])

In [71]:
a[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [72]:
a[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
a[2:]

array([[7, 8, 9]])

In [74]:
a=np.arange(3)
b=np.arange(3,6)

In [75]:
a

array([0, 1, 2])

In [76]:
b

array([3, 4, 5])

In [77]:
a+=1
b+=1

In [78]:
a

array([1, 2, 3])

In [79]:
b

array([4, 5, 6])

In [80]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [81]:
a=np.arange(6)
b=np.arange(7,13)

In [82]:
a.shape=(3,2)

In [83]:
b.shape=(3,2)

In [84]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [85]:
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [86]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  7,  8],
       [ 2,  3,  9, 10],
       [ 4,  5, 11, 12]])

In [87]:
np.concatenate((a,b),axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [88]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [89]:
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [90]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [91]:
np.hstack((a,b))

array([[ 0,  1,  7,  8],
       [ 2,  3,  9, 10],
       [ 4,  5, 11, 12]])

In [92]:
np.stack((a,b),axis=0)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [93]:
np.stack((a,b),axis=1)

array([[[ 0,  1],
        [ 7,  8]],

       [[ 2,  3],
        [ 9, 10]],

       [[ 4,  5],
        [11, 12]]])

In [94]:
np.column_stack((a,b))

array([[ 0,  1,  7,  8],
       [ 2,  3,  9, 10],
       [ 4,  5, 11, 12]])

In [95]:
np.row_stack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [96]:
a=np.arange(0,6)

In [97]:
a.shape=(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [98]:
np.split(a,2,0)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [99]:
np.split(a,3,1)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [100]:
np.split(a,[0,1],0)

[array([], shape=(0, 3), dtype=int64), array([[0, 1, 2]]), array([[3, 4, 5]])]

In [101]:
a=np.arange(9)

In [102]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [103]:
a.shape =(3,3)

In [104]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
np.split(a,[1,2],0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]